### ISSUE TITLE
Search Test Case

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#199]
Progress will be confirmed below as it will be prolonged.
Includes refactoring work to create a valid test case.

 ###### IndexType
 - [x]  Class division #197
 - [x]  Test case creation
 - [x]  branch coverage creation (100%)

 ###### DocumentFactory
 - [x]  move to the Analyzer the character transformation process #197
 - [x]  decision table(Simple reference materials) creation #176, #204
 - [x]  Test case creation #204
 - [x]  branch coverage creation #198 (100%)
 - [x]  Visual confirmation by luke(Low priority, Field data type) #204

 ###### AnalyzerFactory
 - [x]  Integration of currently dispersed string processing #197
 - [x]  decision table(Simple reference materials) creation #205 , #208
 - [x]  Test case creation
 - [x]  branch coverage creation #198 (97%)

 ###### QueryFactory
 - [x]  move to the Analyzer the character transformation process #197
 - [x]  Test case creation
 - [x]  branch coverage creation #198 (96%)

 ###### SearchService
 - [x]  Test case creation
 - [x]  branch coverage creation #198 (0%)

**Comment by tesshucom** [comment]
The SearchService test is a temporary bend.
As the scope of intermediate processing has increased and reached a useful level for Agile.
A specification change is made to improve search accuracy.

**Comment by jp-searching** [comment]
Additional aspects of SearchService.
#191
#209
#210
Although it is difficult to create a test case for scanning, it is hoped that it can be checked in the end.
