### ISSUE TITLE
Agenda for v112.2.0

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#2241]
### Overview

The theme of the next version is to speed up scanning. Parallelization was initially considered, but testing on the DS220+ confirmed that it was a pretty bad option (at least for now) , so it was put on hold. Instead, some fixes will be considered to eliminate bottlenecks when dealing with large libraries.

> Remarks : The improvements to be made in v112.2 are the SQL improvements available in the ANSI range. (Simple queries that can be used with any DB). There are some places where speed improvement can be expected by introducing a specific DB Dialect, but that is not the goal in v111.2. For Jpsonic, speeding up scanning isn't the biggest concern. Once some issues are resolved here, we will start fixing features other than scanning to gain more stability. (Index, Podcasts, etc.) The subject of improving scan speed may be covered several times in the future. If there is no problem with this, it will be possible to release with hotfix.

<details>
<summary>Viewpoint</summary>

There are three points that stand out :

 - 1. Unreasonably slow music analysis (Highest percentage of inefficient time)
   - Even if the content of the tag is exactly the same, the analysis time increases as the size of the music byte size increases. Large libraries may not be as fast as expected even with sufficient warm-up. (Simply put, if you have the exact same 100,000 songs in MP3 and FLAC, the MP3 will scan faster.) Unnatural ...
   - #2230 Additional verification would be required. 
   - It is also possible to think that it is a limited problem only for the first scan.  However, the improvement will have the greatest impact.
 - 2. Individual refactoring of scanning procedures (Definitely can be improved)
   - At the moment, realization of the function is prioritized, and not good queries are included. Some Processes can be sped up without affecting functionality.
   - This will be master-merged only if it has a clear impact on scanning speed for a library of 100,000 to 400,000 songs through measurement. (Prevent rework)
 - 3. #1879 (Designing processes that run concurrently with the most expensive scans)
   - Not a scan, but dangerous if run at the same time as a large library scan
   - Well, it would be more natural to think that the original design was not a separate service. Index generation is not a process that lends itself to being done dynamically. As with reflesh of order-field, it is more resource efficient to incorporate the design of that data generation as part of the scan. 
   - Although scanning is complicated, sorting and indexing are inherently inseparable from scanning. To facilitate consistency and better resource control, all critical processing required should be within the design scope of the scan.
   - Excluding the index, the next suspicious thing is the image generation request

Proceed as follows

 - 1. An investigation will be conducted in v112.2.0. Not sure if it is currently resolvable. 
   - In practice, verification under new conditions is necessary. It would be too early to conclude anything at this point.
     - By a method of elimination, it can be estimated that it is probably the seek speed of the disk (how to solve it on the program side is limited)
   - Fixes planned already  for v111.2.0 have higher priority.
 - 2. Mainly, will be fixed in v112.2.0
   - Therefore, **patch releases** are expected. Because it does not change the feature of the scan.
   - If we release after solving everything, it will take time to receive benefits. 
   - Docker images already support automatic updates.
 - 3. Would involve changing the table design, Web page and UPnP. So v113.0.0.

</details>

### Tasks (Improved scan speed)

The following have already been released as hotfixes. Total scan time minus PARSE_FILE_STRUCTURE is half of 112.1.0 for 112.1.8. About 15 minutes for a new scan of 400,000 songs. The total scan time will be PARSE_FILE_STRUCTURE plus it.

The reason we subtract PARSE_FILE_STRUCTURE to measure the effect is that the environment has a very large effect. As described in 'Perspective' - i, it is greatly affected by the performance of the secondary file cache or the difference in hard disk performance such as SSD/HDD.

<details>
<summary>Done</summary>

 - [x] Improve RUN_STATS
   - #2295
   - About 30 seconds for 40 music folders and 400,000 songs. The processing could be done asynchronously, but it won't be fixed further in this phase. For tens of thousands of songs, it's a split second.
 - [x] Improve REFRESH_ALBUM_ID3
 - [x] Improve REFRESH_ARTIST_ID3
   - Some query improvements and small refactorings were attempted. However, most of them worked against speed. Therefore, the status quo will be maintained for some time. If we want more speed than this, you'll probably have to work on per-database dialects and tricks for Connection. This is not done in the current phase.
     - For tens of thousands of songs, it takes only a few seconds, so it's not fatal.
   -  Unlike most *sonic ID3 processing, exact differential verification of all data is performed. A simple speed comparison with these is impossible.
 - [x] Improve UPDATE_SORT_OF_ARTIST
   - #2280
 - [x] Improve UPDATE_SORT_OF_ALBUM
   - #2299
 - [x] Improve PARSE_ALBUM
   - #2252
   - A method using between of id without using limit/offset was also verified. The results were about the same or even slower. (At least in HSQLDB). If the number of songs reaches 100 million, it may need to be improved, but there is not much merit on the scale assumed. Therefore, there is no change in most of the processing. (If we want to make it faster with Postgres, there are other ways)
 - [x] Improve UPDATE_ORDER_OF_ALBUM
   - #2252
 - [x] Improve UPDATE_ORDER_OF_ALBUM_ID3
   - #2252
 - [x] Improve UPDATE_GENRE_MASTER
   - I was planning to simplify it because it is very complicated, but it works without problems, so the status quo will be maintained. Even with 400,000 songs and many genres, the processing time is about 5 seconds. Since it takes less than one second for thousands to tens of thousands, there is no performance problem.  If anything, it may be necessary to fix when the Lucene version is up.
 - [x] Add thread wait
   - #2308

</details>

### Tasks (Other than scanning)

 - [x] Refactoring of sorting logic (done on a regular basis)
   - Done. #2273
 - [x] #2310
