### ISSUE TITLE
Support for phrase search

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#407]
Change the search method to phrase search. Also, the previous search method will be preserved by switching.

 - [x] Migrate query generation to builder pattern #423
 - [x] Lucene update #486
 - [x] Search method switching #487
 - [x] Stopward multiplexing #488
 - [x] Lucene-Document redesign #482
 - [x] HiraganaStopFilter specifications change #489
 - [x] Change Stopward #492
 - [x] Add query generation logic  #483
 - [x] Fix for missing cases #491

related #294

___

#### Whether field design can be simplified (Is it possible to reduce document fields)

Possible. However, in that case, it becomes impossible to distinguish the analyzer and the boost for each field. Field design is maintained.

#### Is it possible to maintain backward compatibility successfully?

The move to phrase search is a relatively simple proposition. Coexistence of legacy and phrase search is a bit complicated.

Because the document design is different , so the switchover during operation of legacy search and phrase search is almost impossible. Search methods cannot be switched and used on-time without increasing the amount of index data.

The alternative is switching, not coexistence. Legacy mode can be retained in Stratogy. The expected behavior when users switch is to restart the server and run the scan. Almost all logic must be strategy. 

#### Required design modifications for phrase search

Legacy logic retention is the basic policy of Jpsonic. It is necessary to multiplex document generation, Analyzer and query generation.

**Comment by tesshucom** [comment]
Increased requirements make testing difficult with current designs.
Implement # 423 first.

**Comment by tesshucom** [comment]
The following items are not practical and significantly reduce index cost performance and are temporarily excluded from the requirements.
 - exact match
 - prefix 

It will be considered if absolutely necessary due to the function of the smart list.
Otherwise it will not be added.

**Comment by tesshucom** [comment]
It seems that it can be handled by branching logic instead of Stratogy.
(But complicated.)

Refactor if necessary when doing #484.

**Comment by tesshucom** [comment]
Need to update index version.
