### ISSUE TITLE
Replace index display entirely

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#630]
Due to the huge size of the Japanese index, current web page indexes are very difficult to use.
Please change to a drawer type.

 - Can be used on tablets
 - Operable with a keyboard.

____

 - [x] Creating a drawer
 - [x] Add an option to close the drawer in the initial state
 - [x] Move unnecessary menus to the drawer when listening to music
 - [x] Change the DOM configuration of the index
 - [x] Add new index page to home
 - [x] Add option to change index access key
 - [x] Adjust the display of radios, playlist and shortcuts
 - [x] ~~Overall style adjustment~~ -> #622
 - [x] Check the operation of shortcut keys because the top page will changed significantly -> Need fix in main frame.
 - [x] ~~Check the operation of refresh because the top page will changed significantly~~ -> #646
 - [x] ~~Change default values ​​for display options.~~ -> #638
 - [x] Change shortcut key that conflicts with browser

**Comment by tesshucom** [comment]
This is not possible with current CSS. Scripts only work in browsers that are compatible with the script. Leave it for a while.

**Comment by tesshucom** [comment]
-> If change the frame structure, it is possible with the current CSS without script.
In any case the current frame composition is deprecated and should be discarded so consider composition with iframe and new CSS

**Comment by tesshucom** [comment]
Integrate Top and Left.
This makes it possible to overlay the index on the main area.

**Comment by tesshucom** [comment]
Make the DOM configuration simpler. Change to view artists without scrolling with overlay.
This improves the tap and click operability, but it slightly changes the keyboard operation.

Therefore, it restores the index to the Home page as previously supported by Subsonic.
This covers the convenience of various devices such as PCs and tablets, keyboards, screen readers, etc.

**Comment by tesshucom** [comment]
Some styles will break but will eventually be adjusted.
